### PR TITLE
seconds 's' added in transition property

### PR DESCRIPTION
**Pull request by jeroenalewijns**
When opening authentication popup the classes ```_has-modal-custom _has-auth-shown``` are added to ```<body>```
```Magento_UI/js/modal/modal.js``` checks for correct transition in css and won't remove the body class when transition is written without the `s` added after the 0.

### CODE REVIEW

**Comment by Leland** [comment]
Good catch, although, wow: that animation is super out of place. It's the only instance of it in the entire theme.
screen recording 2017-08-14 at 09 57 am

**Comment by jeroenalewijns** [comment]
It is for sure but JS checks for the transitions (see https://github.com/magento/magento2/blob/develop/app/code/Magento/Ui/view/base/web/js/modal/modal.js ln29). Quite annoying!

Travis CI fails on gulp-sass-error... why is this removed?

**Comment by Igloczek** [comment]
It was removed by accident. It's fixed on develop branch.

**Comment by jeroenalewijns** [comment]
@Igloczek The problem with the naming of the transitions as described in the start of this pull request isn't merged in the develop branch.

**Pull request merged**
