### PR TITLE
Port hidden labels in from 2.3.2, fixes visual glitches in checkout

### PR DESCRIPTION
**Pull request by amenk**

### CODE REVIEW

**Comment by amenk** [comment]
Bug:

bug

Fixed:

after-patch

**Comment by Krielkip** [comment]
@Igloczek Can you look at this.

**Comment by Stevie-Ray** [comment]
@Igloczek or @Januszpl please have a look at this.

**Comment by Igloczek** [comment]
@amenk Could you provide the source of these changes in the Magento core repository?

**Comment by Stevie-Ray** [comment]
not @amenk but here they are @Igloczek:

https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/app/design/frontend/Magento/blank/Magento_Checkout/web/css/source/module/checkout/_tooltip.less#L59

https://github.com/magento/magento2/blob/7aa94564d85e408baea01abc5315a0441401c375/app/design/frontend/Magento/blank/Magento_Customer/web/css/source/_module.less#L168

**Review by natedawg92 — DISMISSED** [review]

**Review by Stevie-Ray — DISMISSED** [review]

**Review by Januszpl — APPROVED** [review]

**Pull request merged**
