### PR TITLE
Page is unresponsive after closing login popup in checkout

### PR DESCRIPTION
**Pull request by TomFranssen**
In the checkout page when you close the login popup after opening you cannot click anywhere on the page. This is because the backdrop behind the modal doesn't get removed. The JavaScript for the modal at magento/module-ui/view/base/web/js/modal/modal.js looks at the CSS transition property to remove the backdrop. This value for the transition property is invalid that's why the transition property never get's picked up.

### CODE REVIEW

**Comment by Leland** [comment]
You're merging into master – this has already been fixed on develop by #152. @Igloczek maybe time to release? This is a pretty serious bug.

**Review by Januszpl — APPROVED** [review]
CR ok

**Comment by Januszpl** [comment]
Yes. @Igloczek release or hotfix at least.

**Comment by Igloczek** [comment]
@TomFranssen As @Leland mentioned the issue with transitions was already fixed on develop branch, but there is one more change in your code in sidebar column variable. 

Could you explain how it's related to the reported issue?

**Comment by Leland** [comment]
That's from #131

**Comment by Igloczek** [comment]
Ah, okay!
BTW. Expect a release soon.

**Pull request merged**
