### PR TITLE
FIX: missing fontSizeUnitConvert in email-inline

### PR DESCRIPTION
**Pull request by GrimLink**
The email inline styles still use the rem unit.
Which breaks in none web email clients.

### CODE REVIEW

**Review by pykettk — APPROVED** [review]

**Comment by Igloczek** [comment]
@GrimLink Could you provide the source of these changes in the Magento core repository?

**Comment by GrimLink** [comment]
@Igloczek sure.

The Magento [email.less](https://github.com/magento/magento2/blob/5a82cc97b89c8bdf16740904827743f6d42f8343/app/design/frontend/Magento/blank/web/css/email.less#L21) and the [email-inline.less](https://github.com/magento/magento2/blob/5a82cc97b89c8bdf16740904827743f6d42f8343/app/design/frontend/Magento/blank/web/css/email-inline.less#L22) both import the [`source/_email-base.less`](https://github.com/magento/magento2/blob/5a82cc97b89c8bdf16740904827743f6d42f8343/app/design/frontend/Magento/blank/web/css/source/_email-base.less#L41)
Which contains the variable.

**Comment by GrimLink** [comment]
I am closing this PR.
If someone needs it, feel free to reopen a new PR with this change.

**Comment by Igloczek** [comment]
Just FYI, [we are closing this project.](https://github.com/SnowdogApps/magento2-theme-blank-sass/commit/77253d24ab00c05b2b91693fb25aeac4bebfa1de)

**Pull request closed without merging**
