### PR TITLE
[WIP] B2B module support

### PR DESCRIPTION
**Pull request by Igloczek**

### CODE REVIEW

**Comment by Ig0r-M-magic42** [comment]
@Igloczek any update on this one ?

**Comment by Igloczek** [comment]
This feature is not essential for us internally, since we are not using this theme anymore, so it probably will not be finished.
But if you will invest your time and submit PR, we will be happy to merge it.

**Comment by Ig0r-M-magic42** [comment]
@Igloczek can you let me know what was missing from this PR given it was not worked on and pushed forward ?

**Comment by Igloczek** [comment]
It's been like 1.5 years, I don't remember in detail, but I'd guess that it just doesn't compile or the hard parts were skipped for now, because of some LESS magic code that is hard to translate to SASS.

**Comment by Ig0r-M-magic42** [comment]
> It's been like 1.5 years, I don't remember in detail, but I'd guess that it just doesn't compile or the hard parts were skipped for now, because of some LESS magic code that is hard to translate to SASS.

Thanks for the reply

**Comment by Igloczek** [comment]
[We are closing this project.](https://github.com/SnowdogApps/magento2-theme-blank-sass/commit/77253d24ab00c05b2b91693fb25aeac4bebfa1de)

**Pull request closed without merging**
